services:
  sl:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MIRROR_URL: http://mirror.arvancloud.ir/alpine/v3.21/main
    container_name: sl
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8050:1080"
    volumes:
      - ./vpns/:/vpn:ro
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      OPENVPN_CONFIG: /vpn/config.ovpn
      # SOCKS5_USER: user
      # SOCKS5_PASS: pass
